version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    ports:
      - "9001:9000"
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8383:80"
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: interview_quiz
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: